### ISSUE TITLE
Is this info is correct

### ISSUE THREAD

**Issue by ahmed-bermawy** [nagi1/middle-east-cities#1]
While I'm checking the JSON file for Egypt I found a new city called Barcelona 
when I search with Wikidata id I found that is called Helwan 
```
		{
			"id": 26576,
			"wikiDataId": "Q771345",
			"type": "CITY",
			"city": "Barcelona",
			"name": "برشلونة",
			"country": "مصر",
			"countryCode": "EG",
			"region": "محافظة القاهرة",
			"regionCode": "C",
			"latitude": 29.841944444,
			"longitude": 31.334166666
		},
```

**Comment by nagi1** [comment]
Thanks for the heads up on this, I also know that this database missing important cities like october 6th city, maddenty and shikh zaid.

I'll fix the "Barcelona" city, If you have the time make BR with the cities you know.

Thanks again.
